services:
  quiz-db:
    image: image baze
    container_name: ime container-a
    networks:
      - ime network-a
    environment:
      - niz environment varijabli potrebnih container-u
    volumes:
      - ime volumena : putanja unutar container-a
    ports:
      - "port na lokalnom računalu : port u container-u"

  quiz-backend:
    build:
      context: putanja do backend Dockerfile-a
    container_name: ime container-a
    networks:
      - ime network-a
    environment:
      - niz environment varijabli potrebnih container-u
    ports:
      - "port na lokalnom računalu : port u container-u"
    depends_on:
      - niz container-a koji se moraju pokrenuti prije ovoga

  quiz-frontend:
    build:
      context: putanja do frontend Dockerfile-a
    container_name: ime container-a
    networks:
      - ime network-a
    ports:
      - "port na lokalnom računalu : port u container-u"

networks:
  ime network-a kojeg želimo stvoriti:

volumes:
  ime volume-a kojeg želimo stvoriti: