version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: quiz-frontend
    ports:
      - "5173:5173"

  app:
    build:
      context: ./backend
    container_name: quiz-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quiz_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: quiz-db
    environment:
      - POSTGRES_DB=quiz_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres-data:
