FROM base image s DockerHub-a

WORKDIR direktorij unutar image-a

COPY izvor odredište

RUN java komanda za packaganje jar-a 

RUN preimenovanje jar-a 

EXPOSE port na kojem se aplikacija pokreće

ENTRYPOINT komanda argument1 argument2