FROM gradle:8.13-jdk17

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y dos2unix

RUN dos2unix gradlew && chmod +x gradlew

RUN ./gradlew bootJar --no-daemon

RUN sh -c 'cp build/libs/*.jar app.jar'

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]